language: php

php:
  - '7.0'

env:
  global:
    - BUILD_LEADER_ID=1

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - npm run lint
  - npm run build

jobs:
  include:
    - stage: release
      php: '7.0'
      install:
        - composer install --prefer-dist --no-interaction --optimize-autoloader
        - nvm install 8
        - nvm use 8
        - npm install
      script:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
