language: php

php:
  - '7.0'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_install:
  - nvm install 8
  - nvm use 8

install:
  - npm install
  - composer install --prefer-dist

script:
  - npm run lint
  - npm run build

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
